src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=254, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $salutation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $secondname;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    private $profilePicture;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $registerCode;

    /**
     * @ORM\Column(type="boolean")
     */
    private $activate;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $passwordResetCode;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $passwordResetCodeTime;

    /**
     * @ORM\Column(name="created", type="datetime",nullable=true)
     */
    private $created;

    /**
     * @ORM\Column(type="boolean")
     */
    private $firstLogin;

    /**
     * @ORM\OneToMany(targetEntity=Media::class, mappedBy="user")
     */
    private $media;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=4096)
     */
    private $plainPassword;

    public function __construct()
    {
        $this->media = new ArrayCollection();
        $this->isActive = true;
        $this->players = new ArrayCollection();
    }

    public function eraseCredentials()
    {
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = $email;
    }


    public function getRoles()
    {
        return array('ROLE_USER');
    }

    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }
    
    public function getId(): ?string
    {
        return $this->id;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getSalutation(): ?string
    {
        return $this->salutation;
    }

    public function setSalutation(?string $salutation): self
    {
        $this->salutation = $salutation;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getSecondName(): ?string
    {
        return $this->secondname;
    }

    public function setSecondName(string $secondName): self
    {
        $this->secondname = $secondName;

        return $this;
    }

    public function getProfilePicture()
    {
        if($this->profilePicture != null)
        {
            return stream_get_contents($this->profilePicture);
        }
        return null;
        
    }

    public function setProfilePicture($profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    public function getRegisterCode(): ?string
    {
        return $this->registerCode;
    }

    public function setRegisterCode(?string $registerCode): self
    {
        $this->registerCode = $registerCode;

        return $this;
    }

    public function getActivate(): ?bool
    {
        return $this->activate;
    }

    public function setActivate(bool $activate): self
    {
        $this->activate = $activate;

        return $this;
    }

    public function getPasswordResetCode(): ?string
    {
        return $this->passwordResetCode;
    }

    public function setPasswordResetCode(?string $passwordResetCode): self
    {
        $this->passwordResetCode = $passwordResetCode;

        return $this;
    }

    public function getPasswordResetCodeTime(): ?\DateTimeInterface
    {
        return $this->passwordResetCodeTime;
    }

    public function setPasswordResetCodeTime(?\DateTimeInterface $passwordResetCodeTime): self
    {
        $this->passwordResetCodeTime = $passwordResetCodeTime;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }


    public function getFirstLogin(): ?bool
    {
        return $this->firstLogin;
    }

    public function setFirstLogin(bool $firstLogin): self
    {
        $this->firstLogin = $firstLogin;

        return $this;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    /**
     * @return Collection|Media[]
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function getVideoMedia(): Collection
    {
        return $this->media->filter(function(Media $media){
            return $media->getType() == Media::$MEDIA_TYP_VIDEO;
        });
    }

    public function getImageMedia(): Collection
    {
       return $this->media->filter(function(Media $media){
            return $media->getType() == Media::$MEDIA_TYP_IMAGE;
        });
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media[] = $medium;
            $medium->setUser($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->contains($medium)) {
            $this->media->removeElement($medium);
            // set the owning side to null (unless already changed)
            if ($medium->getUser() === $this) {
                $medium->setUser(null);
            }
        }

        return $this;
    }

    public function getUsedStorageInBytes()
    {
        $usedBytes = 0;
        $mediaList = $this->getMedia();

        foreach ($mediaList as $media)
        {
            $usedBytes = $usedBytes + $media->getSize();
        }
        return $usedBytes;
    }

    public function getUsername(): string
    {
        return (string) $this->email;
    }
}

src/Controller/Media/MediaController.php
<?php

namespace App\Controller\Media;
use App\Controller\Service\AWSController;
use App\Entity\Media;
use Exception;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Controller\Base\BaseUserController;
use Symfony\Component\HttpFoundation\Request;
use App\util\Utilities;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class MediaController extends BaseUserController
{

    /**
     * @Route("/upload")
     * @IsGranted("ROLE_USER")
     */
    public function upload()
    {
        try
        {
            $breadcrumbPath = array();
            $breadcrumbPath[]  = array(
                "Url" => "/upload",
                "Name" => $this->getLanguageStringValue("uploadMedia")
            );
            return $this->renderTemplate('/media/upload.html.twig', [
                'SiteName' => $this->getLanguageStringValue("uploadMedia"),
                'NavName' => 'Upload',
                'UsedStorageByte' => $this->getUser()->getUsedStorageInBytes(),
                'BreadcrumbPath' => $breadcrumbPath
            ]);
        }
        catch (Exception $exception)
        {
            $this->getLogger()->error($exception);
        }
    }

    /**
     * @Route("/videos", methods={"GET"})
     * @IsGranted("ROLE_USER")
     */
    public function videos(Request $request)
    {
        try {
            if($request->get("output") == "json")
            {
                $media = $this->getDoctrine()->getRepository(Media::class)->findBy(["type"=>Media::$MEDIA_TYP_VIDEO, "user"=>$this->getUser()]);
                $inserts = ["inserts" => []];
                foreach ($media as $medium)
                {
                    $inserts["inserts"][] = (object) [
                        'id' => $medium->getId(),
                        'src' => $medium->getPath(),
                        'thumbnail' => $medium->getThumbnail(),
                        'type' => $medium->getType(),
                    ];
                }
                return new JsonResponse($inserts);
            }
            else
            {
                $breadcrumbPath = array();
                $breadcrumbPath[]  = array(
                    "Url" => "/videos",
                    "Name" => $this->getLanguageStringValue("videos")
                );
                return $this->renderTemplate('/media/videos/videos.html.twig', [
                    'SiteName' => $this->getLanguageStringValue("videos"),
                    'NavName' => 'Videos',
                    'UsedStorageByte' => $this->getUser()->getUsedStorageInBytes(),
                    'BreadcrumbPath' => $breadcrumbPath
                ]);
            }
        }
        catch (Exception $exception)
        {
            $this->getLogger()->error($exception);
        }
    }

    /**
     * @Route("/images" ,methods={"GET"})
     * @IsGranted("ROLE_USER")
     */
    public function images(Request $request)
    {
        try {
            if($request->get("output") == "json")
            {
                $media = $this->getDoctrine()->getRepository(Media::class)->findBy(["type"=>Media::$MEDIA_TYP_IMAGE, "user"=>$this->getUser()]);
                $inserts = ["inserts" => []];
                foreach ($media as $medium)
                {
                    $inserts["inserts"][] = (object) [
                        'id' => $medium->getId(),
                        'src' => $medium->getPath(),
                        'thumbnail' => $medium->getThumbnail(),
                        'type' => $medium->getType(),
                    ];
                }
                return new JsonResponse($inserts);
            }
            else
            {
                $breadcrumbPath = array();
                $breadcrumbPath[]  = array(
                    "Url" => "/images",
                    "Name" => $this->getLanguageStringValue("pictures")
                );
                return $this->renderTemplate('/media/images/images.html.twig', [
                    'SiteName' => $this->getLanguageStringValue("pictures"),
                    'NavName' => 'Images',
                    'UsedStorageByte' => $this->getUser()->getUsedStorageInBytes(),
                    'BreadcrumbPath' => $breadcrumbPath
                ]);
            }
        }
        catch (Exception $exception)
        {
            $this->getLogger()->error($exception);
        }
    }

    /**
     * @Route("/uploadmedia")
     * @IsGranted("ROLE_USER")
     */
    public function media(Request $request,HttpClientInterface $httpClientInterface,LoggerInterface $logger)
    {
        try {
            $file = $request->files->get('files')[0];
            $category = $request->get('category');
            $tags = $request->get('tags');
            $ageCategory = $request->get('ageCategory');
            $gender = $request->get('gender');
            $filePath = $file->getPathname();
            $fileSize = $file->getSize();
            $tempFile = $file->getFileInfo();
            $mimetype = $file->getMimeType();
            $extension = $file->getClientOriginalExtension();
            $fileOriginalName = $file->getClientOriginalName();
            $uniqFileName = uniqid();


            $base64 = "";
            $mediaType = "";
            if (strpos($file->getMimeType(), "image") !== false) {
                $storeFolder = "uploads" . DIRECTORY_SEPARATOR . "images" . DIRECTORY_SEPARATOR . $this->getUser()->getId();
                $imageBlob = Utilities::scaleImageFileToBlob($filePath);
                $base64 = 'data:image/' . $extension . ';base64,' . base64_encode($imageBlob);
                $mediaType = "image";
            } else {
                $storeFolder = "uploads" . DIRECTORY_SEPARATOR . "videos" . DIRECTORY_SEPARATOR . $this->getUser()->getId();
                $mediaType = "video";
            }

            $mediaFilePath = dirname($_SERVER['DOCUMENT_ROOT'], 1) . DIRECTORY_SEPARATOR . 'mediaFiles' . DIRECTORY_SEPARATOR . $storeFolder;

            $filesystem = new Filesystem();

            if(!$filesystem->exists($mediaFilePath))
            {
                $filesystem->mkdir($mediaFilePath);
            }

            $stream = fopen($filePath, "r");

            $filesystem->dumpFile($mediaFilePath . DIRECTORY_SEPARATOR . $fileOriginalName, stream_get_contents($stream));

            fclose($stream);

            $media = new Media();
            $media->setUser($this->getUser())
                ->setName($fileOriginalName)
                ->setPath($mediaFilePath . DIRECTORY_SEPARATOR . $fileOriginalName)
                ->setType($mediaType)
                ->setThumbnail($base64)
                ->setSize($fileSize)
                ->setUniqueFileName($uniqFileName)
                ->setMediaCategory($category)
                ->setTags($tags)
                ->setAgeCategory($ageCategory)
                ->setGender($gender)
                ->setCreated(new \DateTime());

            $this->getUser()->addMedium($media);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($media);
            $entityManager->flush();

            return Utilities::createSuccessfulResponse($this->getLanguageStringValue("pictureUploaded"),200,['id'=>$media->getId()]);
        }
        catch (\Exception $e)
        {
            $this->getLogger()->error($e);
            return Utilities::createErrorResponse($e->getMessage());
        }

    }

    /**
     * @Route("/setthumbnail")
     * @IsGranted("ROLE_USER")
     */
    public function setThumbnail(Request $request) {
        try {
            $mediaId = $request->request->get('MediaId');
            $thumbnail = $request->request->get('Thumbnail');
            $media = $this->getDoctrine()->getRepository(Media::class)->getMediaById($mediaId,$this->getUser());
            $media->setThumbnail($thumbnail);
            $this->getDoctrine()->getManager()->flush();
        }
        catch (Exception $exception)
        {
            $this->getLogger()->error($exception);
        }
    }

    /**
     * @Route("/removeMedium")
     * @IsGranted("ROLE_USER")
     */
    public function removeMedium(Request $request,HttpClientInterface $httpClientInterface,LoggerInterface $logger){
        try {
            $mediaId = $request->get("MediaId");
            $mediaType = $request->get("MediaType");

            if($mediaId != null && $mediaType != null){
                $media = $this->getDoctrine()->getRepository(Media::class)->findOneBy(["id"=>$mediaId]);
                if($media != null)
                {
                    $this->getDoctrine()->getManager()->remove($media);
                    $awsController = new AWSController($httpClientInterface,$logger,$this->getAppStage());
                    $awsController->deleteMedia($media->getPath());
                    $this->getDoctrine()->getManager()->flush();
                    return Utilities::createSuccessfulResponse($this->getLanguageStringValue("mediaDeleted"));
                }
            }
            return Utilities::createErrorResponse($this->getLanguageStringValue("errorContactAdmin"));
        }
        catch (Exception $e)
        {
            $this->getLogger()->error($e);
            return Utilities::createErrorResponse($this->getLanguageStringValue("cantDeleteMedia"));
        }
    }

    /**
     * @Route("/editMedium")
     * @IsGranted("ROLE_USER")
     */
    public function editMedium(Request $request) {
        try {
            $mediaId = $request->get("MediaId");
            $mediaName = $request->get("MediaName");
            $mediaDescription = $request->get("MediaDescription");
            $mediaType = $request->get("MediaType");

templates/media/images/images.html.twig
{% extends "/defaults/main.html.twig" %}

{% block mainContainerContent %}
<div class="col">
    {% if app.user.imageMedia is empty %}
        <div class="alert alert-info" role="alert">
            {{LanguageStrings.noPictureUploaded}}
        </div>
    {% else %}
        <div class="row mb-2">
            <div class="col-md-2">
                <input class="form-control" id="searchMedia" placeholder="{{LanguageStrings.search}}" />
            </div>
        </div>
        <div class="row mb-2" id="noSearchResult" style="display:none;">
            <div class="col">
                <div class="alert alert-info" role="alert">
                    {{LanguageStrings.noSearchResult}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 animated fadeInRight">
                <div class="ml-0 row">
                    {% for media in app.user.imageMedia|sort((a, b) => a.created < b.created) %}
                        <div class="file-box" data-toggle="modal" data-target="#editMediaModal_{{loop.index0}}">
                            <div class="file">
                                <a href="#">
                                    <div class="image">
                                        {## <img alt="image" class="img-fluid" src="{{AWSURL}}{{media.MediaPath}}"> ##}
                                        <img alt="image" class="img-fluid" src="{{media.thumbnail}}">
                                    </div>
                                    <div class="file-name">
                                        <div class="mediaName">{{media.name}}</div>
                                        <small>{{LanguageStrings.added}}: {{media.created|date("d.m.Y")}}</small>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% for media in app.user.imageMedia|sort((a, b) => a.created < b.created) %}
<div class="modal fade" id="editMediaModal_{{loop.index0}}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="mediaModalLabel">{{LanguageStrings.editPicture}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                    <div name="messages">
                        <div id="success_alert_modal_edit_media_{{loop.index0}}" class="alert alert-success" role="alert" style="display:none;"></div>
                        <div id="error_alert_modal_edit_media_{{loop.index0}}" class="alert alert-danger" role="alert" style="display:none;"></div>
                        <center><div style="display:none;" id="edit_media_spinner_{{loop.index0}}" class="spinner-border text-primary" role="status"></div></center>
                    </div>
                <form>
                    <div class="form-group">
                        <label>{{LanguageStrings.pictureName}}</label>
                        <input id="editMediaName_{{loop.index0}}" name="editMediaName_{{loop.index0}}" type="text" class="form-control" value="{{media.name}}" />
                    </div>
                    <div class="form-group">
                        <label>{{LanguageStrings.description}}</label>
                        <input id="editMediaDescription_{{loop.index0}}" name="mediaNameDescription_{{loop.index0}}" type="text" class="form-control" value="{{media.description}}" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{LanguageStrings.cancel}}</button>
                <button class="btn btn-danger" type="button" onclick="showMediaDeleteModal('{{loop.index0}}')">{{LanguageStrings.deletePicture}}</button>
                <button type="button" id="saveMediaButton_{{loop.index0}}" onclick="editMedia('{{loop.index0}}','{{media.id}}','image')" class="btn btn-primary">{{LanguageStrings.savePicture}}</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% import _self as self %}

{% for media in app.user.imageMedia|sort((a, b) => a.created < b.created) %}
    {{ self.deleteMedia(loop.index0,media,LanguageStrings) }}
{% endfor %}

<script src="./scripts/media.js"></script>
<script>
    $(document).ready(function () {
        setupUppyImg()
    });
</script>
{% endblock mainContainerContent %}

{% macro deleteMedia(index,media,LanguageStrings) %}
<div class="modal fade" id="deleteMedia_{{index}}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteMedia_{{index}}">{{LanguageStrings.deletePicture}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div name="messages">
                    <div id="success_alert_modal_delete_media_{{index}}" class="alert alert-success" role="alert" style="display:none;"></div>
                    <div id="error_alert_modal_delete_media_{{index}}" class="alert alert-danger" role="alert" style="display:none;"></div>
                    <center><div style="display:none;" id="delete_media_spinner_{{index}}" class="spinner-border text-primary" role="status"></div></center>
                </div>
            {{LanguageStrings.shouldDeletePicture}}
            </div>
            <div class="modal-footer">
                <button type="button" id="deleteMediaYesButton_{{index}}" onclick="deleteMedia('{{index}}','{{media.id}}','image')" class="btn btn-danger">{{LanguageStrings.yes}}</button>
                <button type="button" id="deleteMediaNoButton_{{index}}" class="btn btn-success" data-dismiss="modal">{{LanguageStrings.no}}</button>
            </div>
        </div>
    </div>
</div>
{% endmacro %}